name: Check IPTV Resolutions

on:
  schedule:
    - cron: '15 13 * * *'  # 每天23点运行
  workflow_dispatch:  # 手动触发

jobs:
  check_resolutions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests m3u8

    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Run resolution check script
      run: python check_resolutions.py

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add fenbianlv.txt
        git commit -m 'Update resolution results'
        git push
